# Copyright (c) 2021 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
  ## Define deployment-tool-frontend service
  deployment_tool_frontend:
    build:
      context: $PWD
      dockerfile: $PWD/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
    read_only: true
    image: deployment_tool_frontend:${EII_VERSION}
    container_name: deployment_tool_frontend
    hostname: deployment_tool_frontend
    restart: unless-stopped
    ipc: "none"
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    environment:
      AppName: "DeploymentToolFrontend"
      dev_mode: "false"
      PROFILING_MODE: ${PROFILING_MODE}
      no_proxy: ${eii_no_proxy},deployment_tool_backend
      NO_PROXY: ${eii_no_proxy},deployment_tool_backend
      CertType: "zmq,pem"
      DEPLOYMENT_TOOL_BACKEND_PORT: 5100
      DEPLOYMENT_TOOL_BACKEND_HOST: deployment_tool_backend
      PORT: 3100
    ports:
      - 3100:3100
    volumes:
      - vol_dep_tool_fe_data:/app
      - /home/$EII_USER_NAME
      - /tmp:/tmp
    networks:
      - eii
    secrets:
      - cert
      - key
networks:
  eii:
    external:
      name: eii

volumes:
  vol_dep_tool_fe_data:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: ${EII_INSTALL_PATH}/tools_output/deployment-tool-fe/
secrets:
  cert:
    file: certificates/server_cert.pem
  key:
    file: certificates/server_key.pem
