const ActionType = {

// ON_TABVALUE:'ON_TABVALUE',UPDATE_APP_NAME
UPDATE_PROJECT_INFO:'UPDATE_PROJECT_INFO',
UPDATE_MAIN_OBJECT:'UPDATE_MAIN_OBJECT',
UPDATE_MAIN_OBJECT_DROP:'UPDATE_MAIN_OBJECT_DROP',
UPDATE_CONFIG_OBJECT:'UPDATE_CONFIG_OBJECT',
REMOVE_ALL:"REMOVE_ALL",
REFRESH:"REFRESH",
ON_SELECTED_TAB:"ON_SELECTED_TAB",
UPDATE_APP_NAME:"UPDATE_APP_NAME"
};


export default ActionType;
